// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6S7CqvVFb6sxsHzUH9z32IimOmlk5Do',
    appId: '1:1098574382087:web:18428ab4fb550e71b296a2',
    messagingSenderId: '1098574382087',
    projectId: 'speakuptsn-68a3c',
    authDomain: 'speakuptsn-68a3c.firebaseapp.com',
    storageBucket: 'speakuptsn-68a3c.firebasestorage.app',
    measurementId: 'G-SMK2RX1Q89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyActFwjmi_-sFL-uVFEI5qATbKE5H9k39M',
    appId: '1:1098574382087:android:e0fcd72f8b8735ceb296a2',
    messagingSenderId: '1098574382087',
    projectId: 'speakuptsn-68a3c',
    storageBucket: 'speakuptsn-68a3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOi45_uHzNPNlSWYVEkscZRYM1zlncEQ',
    appId: '1:1098574382087:ios:2d95f1a0946addd0b296a2',
    messagingSenderId: '1098574382087',
    projectId: 'speakuptsn-68a3c',
    storageBucket: 'speakuptsn-68a3c.firebasestorage.app',
    iosBundleId: 'com.example.speakupTsnMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOi45_uHzNPNlSWYVEkscZRYM1zlncEQ',
    appId: '1:1098574382087:ios:2d95f1a0946addd0b296a2',
    messagingSenderId: '1098574382087',
    projectId: 'speakuptsn-68a3c',
    storageBucket: 'speakuptsn-68a3c.firebasestorage.app',
    iosBundleId: 'com.example.speakupTsnMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL6S7CqvVFb6sxsHzUH9z32IimOmlk5Do',
    appId: '1:1098574382087:web:9df391d9f9b74f7fb296a2',
    messagingSenderId: '1098574382087',
    projectId: 'speakuptsn-68a3c',
    authDomain: 'speakuptsn-68a3c.firebaseapp.com',
    storageBucket: 'speakuptsn-68a3c.firebasestorage.app',
    measurementId: 'G-G96Y8257FS',
  );

}